#!/bin/sh
# Build the signature-enforcement fixture for T4-CONFEXT-001.
#
# Needs firmware that trusts the confext signer, and needs the artifact to stay
# byte-identical because T3-SLICE-001 and T4-SLICE-001 assert that. So it never
# touches the artifact: it copies and enrolls into the copy.
#
# Through the ESP rather than from inside the guest, which cannot do it --
# efivarfs marks existing variables immutable and the artifact carries no
# chattr. systemd-boot auto-enrolls PK.auth, KEK.auth and db.auth from
# \loader\keys\auto on firmware in setup mode, which a fresh store always is.
#
# All three keys synthetic, enrolled nowhere but a disposable VM's variable
# store, destroyed with the build root. What is measured is whether an
# unenrolled signer is refused, not whose key does the enrolling.
set -eu

build_root=${NEUTRINOS_SLICE_BUILD_ROOT:-${XDG_CACHE_HOME:-$HOME/.cache}/neutrinos/slice}
keys_dir="$build_root/keys"
# Overridable, so the same enrollment runs against the PLN-0002-01 spike
# artifact without a slice composition. Same step either way: the artifact's
# own ESP is what gets written.
artifact=${NEUTRINOS_ENROLL_ARTIFACT:-$build_root/out/neutrinos-slice.raw}
fixture_dir=${NEUTRINOS_ENROLL_FIXTURE_DIR:-$build_root/fixture}
# Fixed name: T4-CONFEXT-001 consumes this directory as a declared capability,
# and a name varying with the artifact would make it guess.
fixture="$fixture_dir/enrolled-artifact.raw"

[ -f "$artifact" ] || { echo "enroll-fixture: no artifact at $artifact" >&2; exit 1; }
image_cert=${NEUTRINOS_ENROLL_IMAGE_CERT:-$keys_dir/secureboot.crt}
[ -f "$image_cert" ] || {
    echo "enroll-fixture: no image-signing certificate at $image_cert;" \
         "db without it produces an unbootable machine" >&2; exit 1; }
# Which verity signer db carries. Overridable so the negative fixture -- db
# trusting a different authority -- needs no second script to drift from this
# one. PLN-0002-06's image-policy matrix passes verity-wrong.crt.
verity_cert=${NEUTRINOS_ENROLL_VERITY_CERT:-$keys_dir/verity.crt}
[ -f "$verity_cert" ] || {
    echo "enroll-fixture: no verity certificate at $verity_cert;" \
         "buildroot.py generates it" >&2; exit 1; }

for tool in sbsiglist sbvarsign mcopy sfdisk; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "enroll-fixture: $tool unavailable on PATH" >&2; exit 1; }
done

mkdir -p "$fixture_dir" "$keys_dir"

owner=$(uuidgen 2>/dev/null || echo 00000000-0000-0000-0000-000000000000)

# The platform key signs the variable updates and is enrolled as PK, taking the
# firmware out of setup mode, so it must exist first. Kept distinct from the
# verity signer, which is what makes "the signer is trusted" a statement about
# db rather than about who built the image.
#
# Generated by buildroot.py, which owns all four subjects of the declaration's
# signing-material table. It used to be generated here, which put two of the
# four in this script and the rest in compose.sh, under guards written twice.
[ -f "$keys_dir/platform.key" ] && [ -f "$keys_dir/platform.der" ] || {
    echo "enroll-fixture: no platform key at $keys_dir; buildroot.py" \
         "generates it" >&2; exit 1; }

# db carries the image signer and the verity signer. The image signer is not
# optional: db with the verity certificate alone is a machine whose firmware
# refuses its own UKI and times out with no console -- measured, by the first
# fixture built here.
#
# The second verity key is absent from db, and that absence is the measurement:
# a confext signed with it carries a valid signature by an untrusted authority.
#
# Derived here rather than taken from compose.sh, so the two scripts' order
# cannot matter, and written beside the fixture rather than into the keys
# directory, since verity-wrong's DER landing on verity.der would corrupt the
# shared directory for every later run.
openssl x509 -outform DER -in "$verity_cert" -out "$fixture_dir/verity.der"

[ -f "$keys_dir/secureboot.der" ] || openssl x509 -outform DER \
    -in "$image_cert" -out "$keys_dir/secureboot.der"

sbsiglist --owner "$owner" --type x509 \
    --output "$fixture_dir/verity.esl" "$fixture_dir/verity.der"
sbsiglist --owner "$owner" --type x509 \
    --output "$fixture_dir/image.esl" "$keys_dir/secureboot.der"
# A signature list is a concatenation of lists, so db is built by appending
# rather than by re-signing one combined certificate.
cat "$fixture_dir/image.esl" "$fixture_dir/verity.esl" >"$fixture_dir/db.esl"
sbsiglist --owner "$owner" --type x509 \
    --output "$fixture_dir/pk.esl" "$keys_dir/platform.der"

# Signed with the platform key. Setup mode accepts the update without verifying
# the signature, but the structure is still required -- an unsigned payload is
# rejected as malformed.
for var in PK KEK db; do
    case $var in
        db) esl="$fixture_dir/db.esl" ;;
        *) esl="$fixture_dir/pk.esl" ;;
    esac
    sbvarsign --key "$keys_dir/platform.key" --cert "$keys_dir/platform.crt" \
        --output "$fixture_dir/$var.auth" "$var" "$esl"
done

cp --reflink=auto "$artifact" "$fixture"

# The ESP offset is read from the artifact's own partition table rather than
# assumed. It has moved once already between spike and slice, and a wrong
# offset here writes into a filesystem that is not the ESP.
offset=$(sfdisk --json "$fixture" | python3 -c '
import json, sys
table = json.load(sys.stdin)["partitiontable"]
sector = table.get("sectorsize", 512)
for partition in table["partitions"]:
    if partition["type"].upper() == "C12A7328-F81F-11D2-BA4B-00A0C93EC93B":
        print(partition["start"] * sector)
        break
else:
    raise SystemExit("no ESP in partition table")
')

mmd -i "$fixture@@$offset" ::/loader ::/loader/keys ::/loader/keys/auto 2>/dev/null || true
for var in PK KEK db; do
    mcopy -o -i "$fixture@@$offset" "$fixture_dir/$var.auth" "::/loader/keys/auto/$var.auth"
done

# Build-side proof that the copy differs only as intended and the artifact was
# not touched. The check re-verifies the digest.
mdir -i "$fixture@@$offset" ::/loader/keys/auto
sha256sum "$artifact" >"$fixture_dir/artifact.sha256"
echo "enroll-fixture: wrote $fixture"
