# SPDX-License-Identifier: LGPL-2.1-or-later
# The authenticated release artifact. Under C-013 this is the whole of it:
# there is no root image, and this partition carries no configuration and no
# state. Minimize=guess keeps the spike small; the format comparison declares
# its own sizing in PLN-0002-05 and does not inherit this.
[Partition]
Type=usr
Label=pln0002-01
Format=erofs
CopyFiles=/usr:/
Verity=data
VerityMatchKey=usr
Minimize=guess
