# SPDX-License-Identifier: LGPL-2.1-or-later
# The detached signature over the root hash. Present so the spike can measure
# both bindings independently -- the UKI command line and the signature
# partition -- rather than assuming they agree.
[Partition]
Type=usr-verity-sig
Label=pln0002-01-verity-sig
Verity=signature
VerityMatchKey=usr
